Make PaperTable public and update kryo libraries
pilgr/Paper pull request #194
Opened 2021-11-16 12:53 UTC by ahmetturk

This pull request fixes the issues #188 #189 #190 #191 #192 #193

2021-11-16 20:28 UTC, pilgr commented
@ahmetturk thank you very much for resolving those issues! I'll take a look as soon as I can

2021-11-16 23:00 UTC, pilgr requested changes
Thanks again for making this long waiting fix! I was trying to apply it and realised that PR contains seems unnecessary changes which also broke unit tests. Please consider making an isolated PR which solve the critical issue and make another PRs if you wish to make other improvements. Thank you!

2021-11-19 02:49 UTC, nabil6391 commented on paperdb/build.gradle
> +    api 'com.esotericsoftware:kryo:5.2.0'
There are major changes from Kyro 4.0.1  to Kyro 5.2.0, which would require a migration as stated below: 

https://github.com/EsotericSoftware/kryo/releases/tag/kryo-parent-5.0.0-RC1

https://github.com/EsotericSoftware/kryo/wiki/Migration-to-v5

I suggest we only fix for #188 and co

2021-12-10 11:17 UTC, Vall0n commented on paperdb/src/main/java/io/paperdb/PaperTable.java
> +public class PaperTable<T> {
Hey @pilgr,
I don't think that this will fix #188. I've tested it and also [commented](https://github.com/pilgr/Paper/issues/188#issuecomment-943113851) on the ticket. 
But maybe this [comment](https://github.com/pilgr/Paper/issues/188#issuecomment-964988408) can help to solve the issue. 
And I still think that the `kryo` library and maybe other dependencies should be updated. Just guessing but maybe that will get rid of the [buffer underflow issue](https://github.com/pilgr/Paper/issues/4), which still occurs on our app. I can create a separate ticket for it, if it is wanted . 

Best regards!

2021-12-21 17:49 UTC, closed without merging